AgriCrop:
  required:
    - id
    - type
    - name
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: >-
    This entity contains a harmonised description of a generic crop. This entity
    is primarily associated with the agricultural vertical and related IoT
    applications.
  properties:
    agroVocConcept:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: ''
      format: uri
    alternateName:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/alternateName
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    harvestingInterval:
      x-ngsi:
        type: Property
      type: array
      description: |
        A list of the recommended harvesting interval date(s) for this crop. Specified using ISO8601 repeating date intervals:

        *interval, description*

        Where interval is in the form of start date/end date

        `--MM-DD/--MM-DD`

        Meaning repeat each year from this start date to this end date.
      items:
        - type: object
          values:
            dateRange:
              type: string
              pattern: '^-[0-1][0-9]-[0-3][0-9]/-[0-1][0-9]-[0-3][0-9]$'
            description:
              type: string
    hasAgriFertiliser:
      x-ngsi:
        type: Relationship
      type: array
      description: 'Reference to the recommended types of fertiliser suitable for growing this crop.'
      items:
        - &ref_0
          anyOf:
            - type: string
              minLength: 1
              maxLength: 256
              pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
            - type: string
              format: uri
    hasAgriPest:
      x-ngsi:
        type: Relationship
        model: "https://schema.org/URL"
      type: array
      description: 'Reference to the pests known to attack this crop.'
      items:
        - *ref_0
    hasAgriSoil:
      x-ngsi:
        type: Relationship
        model: "https://schema.org/URL"
      type: array
      description: 'Reference to the recommended types of soil suitable for growing this crop.'
      items:
        - *ref_0
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      x-ngsi:
        type: Relationship
        model: https://schema.org/URL  
      type: array
      description: ''
      items: *ref_0
    plantingFrom:
      x-ngsi:
        type: Property
      type: array
      description: |
        A list of the recommended planting interval date(s) for this crop. Specified using ISO8601 repeating date intervals:

        *interval, description*
        
        Where interval is in the form of start date/end date

        `--MM-DD/--MM-DD`

        Meaning repeat each year from this start date to this end date.
      items:
        - type: object
          values:
            dateRange:
              type: string
              pattern: '^-[0-1][0-9]-[0-3][0-9]/-[0-1][0-9]-[0-3][0-9]$'
            description:
              type: string
    relatedSource:
      x-ngsi:
        type: Property
      type: array
      description: List of IDs the current entity may have in external applications
      items:
        - type: object
          values:
            application:
              anyOf:
                - type: string
                  minLength: 1
                  maxLength: 256
                  pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
                - type: string
                  format: uri
            applicationEntityId:
              type: string
    source:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/source
    wateringFrequency:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: |
        A description of the recommended watering schedule. A choice from an enumerated list. One of: *daily, weekly, biweekly, monthly, onDemand, other*
