AgriFarm:
  required:
    - id
    - type
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: >-
    This entity contains a harmonised description of a generic farm made up of
    buildings and parcels. This entity is primarily associated with the
    agricultural vertical and related IoT applications.
  properties:
    address:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/address
    alternateName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    areaServed:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    contactPoint:
      x-ngsi:
        type: Property
      type: object
      description: 'Contact information of the farm i.e email, telephone, etc'
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    hasAgriParcel:
      x-ngsi:
        type: Property
      type: array
      description: List of agri parcels belonging to the farm
      items:
        - &ref_0
          anyOf:
            - type: string
              minLength: 1
              maxLength: 256
              pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
            - type: string
              format: uri
    hasBuilding:
      x-ngsi:
        type: Property
      type: array
      description: List of buildings belonging to the farm
      items:
        - *ref_0
    location:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/location
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items: *ref_0
    relatedSource:
      x-ngsi:
        type: Property
      type: array
      description: List of IDs the current entity may have in external applications
      items:
        - type: object
          values:
            application:
              anyOf:
                - type: string
                  minLength: 1
                  maxLength: 256
                  pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
                - type: string
                  format: uri
            applicationEntityId:
              type: string
    source:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
